### PR TITLE
wip: fix sprite picking

### PR DESCRIPTION
**Pull request by bennlich**
I'm taking a stab at a fix for https://github.com/bzztbomb/three_js_gpu_picking/issues/8. I tried the solution @bzztbomb described, but it's not working quite right yet.

First, the size and position of the hitbox were off. Then I manually added the center and rotation uniforms, which are referenced in `sprite_vert`. This seemed to center the hitbox correctly, but the size is still off -- the hitbox is much larger than the rendered sprite.

I wonder if I'm missing a uniform, but I'm also a little confused why manually setting the `center` uniform helped. It seems like `renderBufferDirect()` should be setting that uniform here already: https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1707.

I'm stuck for now -- let me know if anything obvious jumps out.

### CODE REVIEW

**Comment by bzztbomb** [comment]
> I'm stuck for now -- let me know if anything obvious jumps out.

Awesome! I meant to look into this and life got in the way.  

So looking at [the shader](https://github1s.com/mrdoob/three.js/blob/HEAD/src/renderers/shaders/ShaderLib/sprite.glsl.js) it looks like we may need to add the `USE_SIZEATTENUATION` just like three [does here](https://github1s.com/mrdoob/three.js/blob/HEAD/src/renderers/webgl/WebGLProgram.js) ?  This would also need to be a separate material + flag.

Maybe with that change we won't need the uniforms manually set?  I'm not sure about that at the moment.

**Comment by bzztbomb** [comment]
> So looking at [the shader](https://github1s.com/mrdoob/three.js/blob/HEAD/src/renderers/shaders/ShaderLib/sprite.glsl.js) it looks like we may need to add the `USE_SIZEATTENUATION` just like three [does here](https://github1s.com/mrdoob/three.js/blob/HEAD/src/renderers/webgl/WebGLProgram.js) ? This would also need to be a separate material + flag.

It's also possible this will introduce new issues, since we change the camera projection to zoom in on the pixel we care about.  Though, looking at the shader again, I *think* we'll be ok?

**Comment by bennlich** [comment]
> So looking at the shader it looks like we may need to add the USE_SIZEATTENUATION just like three does here ? This would also need to be a separate material + flag.

Woo! Yes! This did the trick.

> Maybe with that change we won't need the uniforms manually set? I'm not sure about that at the moment.

I did still need to set the uniforms manually. The center uniform only gets set for sprite materials [here](https://github.com/mrdoob/three.js/blob/dev/src/renderers/WebGLRenderer.js#L1705-L1709). And I have no idea where the rotation uniform gets set in three, but the picking was broken without it.

I added an attenuated and an unattenuated sprite to the example as tests.

The only thing I notice that is still a little broken is that the transparency of the sprite is not respected during picking. I guess we would need to make the frag shader more sophisticated in order to fix this.

I think this is ready to merge without that, but have a look and let me know what you think!

**Comment by bzztbomb** [comment]
This looks great! Maybe we can move the sprite that occludes the dancing man a bit?  Since we're not respecting transparency (which I think is ok for now!), it can look like the picking is broken.

**Comment by bennlich** [comment]
Moved!

**Pull request merged**
